/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.porto.ui.telecom;

import com.porto.main.PortoMain;
import com.porto.ui.*;
import com.porto.ui.telecom.callbacks.ResetListener;
import java.util.ArrayList;
import java.util.Vector;

/**
 *
 * @author eipps
 */
public class CustomerInformationUI extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public CustomerInformationUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        titlePanel1 = new com.porto.components.TitlePanel();
        jLabel1 = new javax.swing.JLabel();
        innerGradientPanel1 = new com.porto.components.InnerGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerDetailsPanel2 = new com.porto.ui.telecom.CustomerDetailsPanel();
        innerGradientPanel3 = new com.porto.components.InnerGradientPanel();
        mButton1 = new com.porto.components.MButton();
        mButton2 = new com.porto.components.MButton();
        mButton3 = new com.porto.components.MButton();
        innerGradientPanel2 = new com.porto.components.InnerGradientPanel();

        setLayout(new java.awt.BorderLayout());

        titlePanel1.setPreferredSize(new java.awt.Dimension(400, 70));
        titlePanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PORTOBANKING");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        titlePanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        add(titlePanel1, java.awt.BorderLayout.PAGE_START);

        innerGradientPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(customerDetailsPanel2);

        innerGradientPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        innerGradientPanel3.setPreferredSize(new java.awt.Dimension(530, 100));
        innerGradientPanel3.setLayout(new java.awt.GridBagLayout());

        mButton1.setText("BACK");
        mButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionHandler(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 39, 30, 0);
        innerGradientPanel3.add(mButton1, gridBagConstraints);

        mButton2.setText("RESET");
        mButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionHandler(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 30, 0);
        innerGradientPanel3.add(mButton2, gridBagConstraints);

        mButton3.setText("NEXT");
        mButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionHandler(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 66;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 30, 46);
        innerGradientPanel3.add(mButton3, gridBagConstraints);

        innerGradientPanel1.add(innerGradientPanel3, java.awt.BorderLayout.PAGE_END);

        add(innerGradientPanel1, java.awt.BorderLayout.CENTER);

        innerGradientPanel2.setPreferredSize(new java.awt.Dimension(400, 50));

        javax.swing.GroupLayout innerGradientPanel2Layout = new javax.swing.GroupLayout(innerGradientPanel2);
        innerGradientPanel2.setLayout(innerGradientPanel2Layout);
        innerGradientPanel2Layout.setHorizontalGroup(
            innerGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );
        innerGradientPanel2Layout.setVerticalGroup(
            innerGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(innerGradientPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionHandler
        String command = evt.getActionCommand();  
        if(command.equals("NEXT")){
            PortoMain.getInstance().setContentPanel(new PresentAddressUI());
        }
    }//GEN-LAST:event_buttonActionHandler

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.porto.ui.telecom.CustomerDetailsPanel customerDetailsPanel2;
    private com.porto.components.InnerGradientPanel innerGradientPanel1;
    private com.porto.components.InnerGradientPanel innerGradientPanel2;
    private com.porto.components.InnerGradientPanel innerGradientPanel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.porto.components.MButton mButton1;
    private com.porto.components.MButton mButton2;
    private com.porto.components.MButton mButton3;
    private com.porto.components.TitlePanel titlePanel1;
    // End of variables declaration//GEN-END:variables
}
