/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.porto.ui.telecom;
import com.porto.components.InnerGradientPanel;
import com.porto.dao.AadharBarcodeInfoDAO;
import com.toedter.calendar.JDateChooser;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
/**
 *
 * @author eipps
 */
public class POIDetailsPanel extends InnerGradientPanel implements AncestorListener{

    /**
     * Creates new form serviceDetails
     */
    public POIDetailsPanel() {
        initComponents();
        addAncestorListener(this);
    }
    private void initAadhatData(){
        if(AadharBarcodeInfoDAO.getInstance().isDataAvailable()){
            typeofpoitf.setText("AADHAR");
            docnumbertf.setText(AadharBarcodeInfoDAO.getInstance().getUid());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        typeofpoitf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        docnumbertf = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("TYPE OF POI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 105;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 218;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(typeofpoitf, gridBagConstraints);

        jLabel3.setText("DOCUMENT NO.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 82;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 10, 0);
        add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 218;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 10, 10, 0);
        add(docnumbertf, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField docnumbertf;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField typeofpoitf;
    // End of variables declaration//GEN-END:variables

    @Override
    public void ancestorAdded(AncestorEvent event) {
        
    }

    @Override
    public void ancestorRemoved(AncestorEvent event) {
        
    }

    @Override
    public void ancestorMoved(AncestorEvent event) {
        initAadhatData();
    }
    public void reset(){
        docnumbertf.setText("");
        typeofpoitf.setText("");
    }
}
