/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.porto.ui.telecom;

import com.porto.components.InnerGradientPanel;
import com.porto.dao.AadharBarcodeInfoDAO;
import com.porto.dao.CustomerInfoDAO;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;

/**
 *
 * @author eipps
 */
public class PresentAddressPanel extends InnerGradientPanel implements AncestorListener{

    /**
     * Creates new form serviceDetails
     */
    public PresentAddressPanel() {
        initComponents();
        //addAncestorListener(this);
        initAadharData();
    }
    private void initAadharData(){
        if(AadharBarcodeInfoDAO.getInstance().isDataAvailable()){
          streettf.setText(AadharBarcodeInfoDAO.getInstance().getAddress().replace(",", ",\n")); 
          streettf.setEditable(false);
          localitytf.setText(AadharBarcodeInfoDAO.getInstance().getLm().replace(",", ",\n"));
          localitytf.setEditable(false);
          citytf.setText(AadharBarcodeInfoDAO.getInstance().getDist());
          citytf.setEditable(false);
          statetf.setText(AadharBarcodeInfoDAO.getInstance().getState());
          statetf.setEditable(false);
          postalcodetf.setText(AadharBarcodeInfoDAO.getInstance().getPincode());
          postalcodetf.setEditable(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        housenotf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buildingnametf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sectornotf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        citytf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        statetf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        postalcodetf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        streettf = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        localitytf = new javax.swing.JTextArea();

        setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("HOUSE NO./FLAT NO.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 56;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 218;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(housenotf, gridBagConstraints);

        jLabel3.setText("BUILDING NAME");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 82;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 218;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 10, 0, 0);
        add(buildingnametf, gridBagConstraints);

        jLabel4.setText("SECTOR NO.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 103;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 218;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 10, 0, 0);
        add(sectornotf, gridBagConstraints);

        jLabel6.setText("STREET/ ADDRESS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 76;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        add(jLabel6, gridBagConstraints);

        jLabel7.setText("LOCALITY");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        add(jLabel7, gridBagConstraints);

        jLabel8.setText("CITY");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 146;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        add(jLabel8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 218;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 10, 0, 0);
        add(citytf, gridBagConstraints);

        jLabel11.setText("STATE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 137;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 0);
        add(jLabel11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 218;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 10, 0, 0);
        add(statetf, gridBagConstraints);

        jLabel12.setText("POSTAL CODE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 95;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 21, 0);
        add(jLabel12, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 218;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 10, 21, 0);
        add(postalcodetf, gridBagConstraints);

        streettf.setColumns(20);
        streettf.setRows(5);
        jScrollPane1.setViewportView(streettf);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 10, 0, 0);
        add(jScrollPane1, gridBagConstraints);

        localitytf.setColumns(20);
        localitytf.setRows(5);
        jScrollPane2.setViewportView(localitytf);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 0, 0);
        add(jScrollPane2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    private void setCustomerinfo(){
         CustomerInfoDAO.getInstance().setHouseNo(housenotf.getText());
         CustomerInfoDAO.getInstance().setBuildingName(buildingnametf.getText());
         CustomerInfoDAO.getInstance().setSectorNo(sectornotf.getText());
         CustomerInfoDAO.getInstance().setAddress(streettf.getText());
         CustomerInfoDAO.getInstance().setLocality(localitytf.getText());
         CustomerInfoDAO.getInstance().setCity(citytf.getText());
         CustomerInfoDAO.getInstance().setState(statetf.getText());
         CustomerInfoDAO.getInstance().setPincode(postalcodetf.getText());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buildingnametf;
    private javax.swing.JTextField citytf;
    private javax.swing.JTextField housenotf;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea localitytf;
    private javax.swing.JTextField postalcodetf;
    private javax.swing.JTextField sectornotf;
    private javax.swing.JTextField statetf;
    private javax.swing.JTextArea streettf;
    // End of variables declaration//GEN-END:variables

    @Override
    public void ancestorAdded(AncestorEvent event) {
    }

    @Override
    public void ancestorRemoved(AncestorEvent event) {
       
    }

    @Override
    public void ancestorMoved(AncestorEvent event) {
       //initAadharData();
       //setCustomerinfo();
    }
    public void reset() {
         buildingnametf.setText("");
        citytf.setText("");
        housenotf.setText("");
        localitytf.setText("");
        postalcodetf.setText("");
        sectornotf.setText("");
        statetf.setText("");
        streettf.setText("");
    }
}
