/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.porto.ui;

/**
 *
 * @author eipps
 */
public class DUMMYUI extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public DUMMYUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel1 = new com.porto.components.TitlePanel();
        jLabel1 = new javax.swing.JLabel();
        innerGradientPanel1 = new com.porto.components.InnerGradientPanel();
        innerGradientPanel2 = new com.porto.components.InnerGradientPanel();

        setLayout(new java.awt.BorderLayout());

        titlePanel1.setPreferredSize(new java.awt.Dimension(400, 70));
        titlePanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PORTOBANKING");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        titlePanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        add(titlePanel1, java.awt.BorderLayout.PAGE_START);

        innerGradientPanel1.setLayout(new java.awt.GridBagLayout());
        add(innerGradientPanel1, java.awt.BorderLayout.CENTER);

        innerGradientPanel2.setPreferredSize(new java.awt.Dimension(400, 50));

        javax.swing.GroupLayout innerGradientPanel2Layout = new javax.swing.GroupLayout(innerGradientPanel2);
        innerGradientPanel2.setLayout(innerGradientPanel2Layout);
        innerGradientPanel2Layout.setHorizontalGroup(
            innerGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        innerGradientPanel2Layout.setVerticalGroup(
            innerGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(innerGradientPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.porto.components.InnerGradientPanel innerGradientPanel1;
    private com.porto.components.InnerGradientPanel innerGradientPanel2;
    private javax.swing.JLabel jLabel1;
    private com.porto.components.TitlePanel titlePanel1;
    // End of variables declaration//GEN-END:variables
}
